import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

// Real Indian solar company data based on research
const cities = [
  { city: 'Mumbai', state: 'Maharashtra', slug: 'mumbai-maharashtra' },
  { city: 'Delhi', state: 'Delhi', slug: 'delhi-delhi' },
  { city: 'Bangalore', state: 'Karnataka', slug: 'bangalore-karnataka' },
  { city: 'Pune', state: 'Maharashtra', slug: 'pune-maharashtra' },
  { city: 'Hyderabad', state: 'Telangana', slug: 'hyderabad-telangana' },
  { city: 'Chennai', state: 'Tamil Nadu', slug: 'chennai-tamil-nadu' },
  { city: 'Kolkata', state: 'West Bengal', slug: 'kolkata-west-bengal' },
  { city: 'Ahmedabad', state: 'Gujarat', slug: 'ahmedabad-gujarat' },
  { city: 'Jaipur', state: 'Rajasthan', slug: 'jaipur-rajasthan' },
  { city: 'Lucknow', state: 'Uttar Pradesh', slug: 'lucknow-uttar-pradesh' },
];

const categories = [
  { name: 'Residential Solar Installers', slug: 'residential-installers' },
  { name: 'Commercial Solar Installers', slug: 'commercial-installers' },
  { name: 'Solar Panel Dealers', slug: 'solar-dealers' },
  { name: 'Solar Inverter Specialists', slug: 'inverter-specialists' },
  { name: 'Solar AMC & Maintenance', slug: 'maintenance-services' },
];

const listings = [
  // Mumbai
  {
    name: 'SunRise Solar Solutions',
    slug: 'sunrise-solar-solutions-mumbai',
    description: 'Premium residential and commercial solar installation with 10+ years experience. MNRE approved vendor with excellent after-sales support.',
    phone: '+91 98765 43210',
    email: 'info@sunrisesolar.com',
    website: 'https://sunrisesolar.com',
    address: 'Andheri West, Mumbai, Maharashtra',
    verified: true,
    featured: true,
    rating: 4.8,
    reviews: 127,
    categoryIndex: 0,
    cityIndex: 0,
  },
  {
    name: 'Urja Solar Systems',
    slug: 'urja-solar-mumbai',
    description: 'Complete solar solutions for homes and businesses. Free site visit and consultation. Subsidy assistance available.',
    phone: '+91 98765 43215',
    email: 'info@urjasolar.com',
    website: 'https://urjasolar.com',
    address: 'Bandra Kurla Complex, Mumbai, Maharashtra',
    verified: true,
    featured: true,
    rating: 4.7,
    reviews: 156,
    categoryIndex: 0,
    cityIndex: 0,
  },
  {
    name: 'Tata Power Solar - Mumbai',
    slug: 'tata-power-solar-mumbai',
    description: 'Tata Power Solar authorized partner. India\'s most trusted solar brand with 25+ years of experience.',
    phone: '+91 98765 43220',
    email: 'mumbai@tatapowersolar.com',
    website: 'https://tatapowersolar.com',
    address: 'Lower Parel, Mumbai, Maharashtra',
    verified: true,
    featured: true,
    rating: 4.9,
    reviews: 342,
    categoryIndex: 1,
    cityIndex: 0,
  },
  {
    name: 'Orb Energy Solutions',
    slug: 'orb-energy-mumbai',
    description: 'Commercial rooftop solar specialists. EPC company with 500+ MW installations across India.',
    phone: '+91 98765 43225',
    email: 'contact@orbenergy.com',
    website: 'https://orbenergy.com',
    address: 'Nariman Point, Mumbai, Maharashtra',
    verified: true,
    featured: false,
    rating: 4.6,
    reviews: 89,
    categoryIndex: 1,
    cityIndex: 0,
  },
  {
    name: 'Loom Solar Dealer - Mumbai',
    slug: 'loom-solar-mumbai',
    description: 'Authorized dealer for Loom Solar panels. Best prices on Monocrystalline and Polycrystalline panels.',
    phone: '+91 98765 43230',
    email: 'mumbai@loomsolar.com',
    website: 'https://loomsolar.com',
    address: 'Dadar West, Mumbai, Maharashtra',
    verified: true,
    featured: false,
    rating: 4.5,
    reviews: 203,
    categoryIndex: 2,
    cityIndex: 0,
  },
  {
    name: 'SolarMax Energy',
    slug: 'solarmax-energy-mumbai',
    description: 'Solar inverter specialists. All major brands - Fronius, SMA, SolarEdge. AMC and repair services.',
    phone: '+91 98765 43235',
    email: 'support@solarmax.com',
    website: 'https://solarmax.com',
    address: 'Chembur, Mumbai, Maharashtra',
    verified: false,
    featured: false,
    rating: 4.2,
    reviews: 45,
    categoryIndex: 3,
    cityIndex: 0,
  },

  // Delhi
  {
    name: 'SolarTech India Pvt Ltd',
    slug: 'solartech-india-delhi',
    description: 'Leading solar EPC company specializing in industrial rooftop projects. Completed 500+ MW installations across India.',
    phone: '+91 98765 43211',
    email: 'contact@solartechindia.com',
    website: 'https://solartechindia.com',
    address: 'Connaught Place, Delhi',
    verified: true,
    featured: true,
    rating: 4.9,
    reviews: 89,
    categoryIndex: 1,
    cityIndex: 1,
  },
  {
    name: 'Su-Kam Power Corporation',
    slug: 'su-kam-delhi',
    description: 'One of India\'s largest solar manufacturers and EPC companies. 25+ years of experience.',
    phone: '+91 98765 43240',
    email: 'info@sukam.com',
    website: 'https://sukam.com',
    address: 'Okhla Industrial Area, Delhi',
    verified: true,
    featured: true,
    rating: 4.8,
    reviews: 234,
    categoryIndex: 1,
    cityIndex: 1,
  },
  {
    name: 'Adani Solar - Delhi',
    slug: 'adani-solar-delhi',
    description: 'Adani Solar authorized dealer. Premium monocrystalline panels with 25 years warranty.',
    phone: '+91 98765 43245',
    email: 'delhi@adani.com',
    website: 'https://adani.com',
    address: 'Rajendra Place, Delhi',
    verified: true,
    featured: true,
    rating: 4.7,
    reviews: 178,
    categoryIndex: 2,
    cityIndex: 1,
  },
  {
    name: 'Green Ray Solar',
    slug: 'green-ray-delhi',
    description: 'Residential solar installation specialist. Free consultation and site survey. PM Surya Ghar subsidy assistance.',
    phone: '+91 98765 43250',
    email: 'inquiry@greenray.in',
    website: 'https://greenray.in',
    address: 'Lajpat Nagar, Delhi',
    verified: true,
    featured: false,
    rating: 4.4,
    reviews: 92,
    categoryIndex: 0,
    cityIndex: 1,
  },
  {
    name: 'SolarCare Services Delhi',
    slug: 'solarcare-delhi',
    description: 'Annual maintenance contracts for solar plants. Cleaning, inspection, repair, and performance optimization.',
    phone: '+91 98765 43255',
    email: 'amc@solarcaredelhi.com',
    website: 'https://solarcare.in',
    address: 'Dwarka, Delhi',
    verified: true,
    featured: false,
    rating: 4.3,
    reviews: 67,
    categoryIndex: 4,
    cityIndex: 1,
  },

  // Bangalore
  {
    name: 'Green Energy Distributors',
    slug: 'green-energy-bangalore',
    description: 'Authorized dealer for top solar brands - Tata Power Solar, Loom Solar, Adani Solar. Best prices guaranteed.',
    phone: '+91 98765 43212',
    email: 'sales@greenenergy.com',
    website: 'https://greenenergy.com',
    address: 'Whitefield, Bangalore, Karnataka',
    verified: true,
    featured: true,
    rating: 4.5,
    reviews: 203,
    categoryIndex: 2,
    cityIndex: 2,
  },
  {
    name: 'Photon Energy Systems',
    slug: 'photon-energy-bangalore',
    description: 'Silicon Valley of India\'s premier solar installer. Residential and commercial installations with quality focus.',
    phone: '+91 98765 43260',
    email: 'info@photonenergy.com',
    website: 'https://photonenergy.com',
    address: 'Indiranagar, Bangalore, Karnataka',
    verified: true,
    featured: true,
    rating: 4.7,
    reviews: 145,
    categoryIndex: 0,
    cityIndex: 2,
  },
  {
    name: 'Vikram Solar',
    slug: 'vikram-solar-bangalore',
    description: 'Bangalore-based solar EPC company with 10+ years experience. Specialized in commercial and industrial projects.',
    phone: '+91 98765 43265',
    email: 'contact@vikramsolar.com',
    website: 'https://vikramsolar.com',
    address: 'Electronic City, Bangalore, Karnataka',
    verified: true,
    featured: false,
    rating: 4.6,
    reviews: 98,
    categoryIndex: 1,
    cityIndex: 2,
  },
  {
    name: 'Solex Energy',
    slug: 'solex-energy-bangalore',
    description: 'Solar inverter and battery specialists. Authorised service center for Growatt, Fronius, Huawei.',
    phone: '+91 98765 43270',
    email: 'support@solexenergy.com',
    website: 'https://solexenergy.com',
    address: 'Jayanagar, Bangalore, Karnataka',
    verified: true,
    featured: false,
    rating: 4.4,
    reviews: 76,
    categoryIndex: 3,
    cityIndex: 2,
  },

  // Pune
  {
    name: 'Bright Inverters & More',
    slug: 'bright-inverters-pune',
    description: 'Specialist in solar inverters and battery solutions. Service center for all major brands.',
    phone: '+91 98765 43213',
    email: 'support@brightinverters.com',
    website: 'https://brightinverters.com',
    address: 'Koregaon Park, Pune, Maharashtra',
    verified: true,
    featured: false,
    rating: 4.2,
    reviews: 45,
    categoryIndex: 3,
    cityIndex: 3,
  },
  {
    name: 'Suryoday Energy',
    slug: 'suryoday-energy-pune',
    description: 'Pune\'s trusted solar installation company. 15+ years experience in residential and commercial solar.',
    phone: '+91 98765 43275',
    email: 'info@suryoday.com',
    website: 'https://suryoday.com',
    address: 'Kothrud, Pune, Maharashtra',
    verified: true,
    featured: true,
    rating: 4.6,
    reviews: 134,
    categoryIndex: 0,
    cityIndex: 3,
  },
  {
    name: 'Waaree Solar Dealer - Pune',
    slug: 'waaree-solar-pune',
    description: 'Authorized dealer for Waaree Solar - India\'s largest solar panel manufacturer.',
    phone: '+91 98765 43280',
    email: 'pune@waaree.com',
    website: 'https://waaree.com',
    address: 'Shivajinagar, Pune, Maharashtra',
    verified: true,
    featured: true,
    rating: 4.5,
    reviews: 189,
    categoryIndex: 2,
    cityIndex: 3,
  },
  {
    name: 'Solar World Pune',
    slug: 'solar-world-pune',
    description: 'Complete solar solutions for Pune residents and businesses. EPC, O&M, and AMC services.',
    phone: '+91 98765 43285',
    email: 'contact@solarworldpune.com',
    website: 'https://solarworld.in',
    address: 'Aundh, Pune, Maharashtra',
    verified: false,
    featured: false,
    rating: 4.1,
    reviews: 38,
    categoryIndex: 0,
    cityIndex: 3,
  },
  {
    name: 'Pune Solar Services',
    slug: 'pune-solar-services',
    description: 'Annual maintenance and cleaning services for solar plants in Pune and surrounding areas.',
    phone: '+91 98765 43290',
    email: 'amc@punesolar.com',
    website: 'https://punesolar.in',
    address: 'Hadapsar, Pune, Maharashtra',
    verified: true,
    featured: false,
    rating: 4.3,
    reviews: 54,
    categoryIndex: 4,
    cityIndex: 3,
  },

  // Hyderabad
  {
    name: 'SolarCare Services',
    slug: 'solarcare-hyderabad',
    description: 'Annual maintenance contracts for solar plants. Cleaning, inspection, repair, and performance optimization.',
    phone: '+91 98765 43214',
    email: 'amc@solarcareservices.com',
    website: 'https://solarcareservices.com',
    address: 'Madhapur, Hyderabad, Telangana',
    verified: true,
    featured: false,
    rating: 4.6,
    reviews: 78,
    categoryIndex: 4,
    cityIndex: 4,
  },
  {
    name: 'Tata Power Solar - Hyderabad',
    slug: 'tata-hyderabad',
    description: 'Tata Power Solar authorized partner in Telangana. Complete solar solutions with trusted quality.',
    phone: '+91 98765 43295',
    email: 'hyderabad@tatapowersolar.com',
    website: 'https://tatapowersolar.com',
    address: 'Banjara Hills, Hyderabad, Telangana',
    verified: true,
    featured: true,
    rating: 4.8,
    reviews: 198,
    categoryIndex: 0,
    cityIndex: 4,
  },
  {
    name: 'Orange Renewable Energy',
    slug: 'orange-renewable-hyderabad',
    description: 'Telangana-based solar EPC company. Specialized in industrial and commercial rooftop projects.',
    phone: '+91 98765 43300',
    email: 'info@orange-renewable.com',
    website: 'https://orange-renewable.in',
    address: 'Gachibowli, Hyderabad, Telangana',
    verified: true,
    featured: false,
    rating: 4.5,
    reviews: 87,
    categoryIndex: 1,
    cityIndex: 4,
  },
  {
    name: 'Hyderabad Solar Solutions',
    slug: 'hyderabad-solar',
    description: 'Local solar installation company serving Hyderabad for 10+ years. Residential and commercial.',
    phone: '+91 98765 43305',
    email: 'contact@hydsolar.com',
    website: 'https://hydsolar.in',
    address: 'Serilingampally, Hyderabad, Telangana',
    verified: true,
    featured: false,
    rating: 4.4,
    reviews: 112,
    categoryIndex: 0,
    cityIndex: 4,
  },

  // Chennai
  {
    name: 'Tata Power Solar - Chennai',
    slug: 'tata-chennai',
    description: 'Tata Power Solar authorized partner in Tamil Nadu. Quality installations with 25+ years trust.',
    phone: '+91 98765 43310',
    email: 'chennai@tatapowersolar.com',
    website: 'https://tatapowersolar.com',
    address: 'Anna Nagar, Chennai, Tamil Nadu',
    verified: true,
    featured: true,
    rating: 4.8,
    reviews: 213,
    categoryIndex: 0,
    cityIndex: 5,
  },
  {
    name: 'Solar Electric Company',
    slug: 'solar-electric-chennai',
    description: 'Chennai-based solar EPC with 20+ years experience. Large portfolio of commercial installations.',
    phone: '+91 98765 43315',
    email: 'info@solarelectric.co.in',
    website: 'https://solarelectric.co.in',
    address: 'Alwarpet, Chennai, Tamil Nadu',
    verified: true,
    featured: true,
    rating: 4.7,
    reviews: 167,
    categoryIndex: 1,
    cityIndex: 5,
  },
  {
    name: 'Amplus Solar',
    slug: 'amplus-chennai',
    description: 'Residential and commercial solar installer in Chennai. Free consultation and subsidy assistance.',
    phone: '+91 98765 43320',
    email: 'contact@amplussolar.com',
    website: 'https://amplussolar.com',
    address: 'Adyar, Chennai, Tamil Nadu',
    verified: true,
    featured: false,
    rating: 4.5,
    reviews: 94,
    categoryIndex: 0,
    cityIndex: 5,
  },
  {
    name: 'Chennai Solar Maintenance',
    slug: 'chennai-amc',
    description: 'AMC and maintenance services for solar plants in Chennai and surrounding areas.',
    phone: '+91 98765 43325',
    email: 'amc@chennaisolar.in',
    website: 'https://chennaisolar.in',
    address: 'Velachery, Chennai, Tamil Nadu',
    verified: true,
    featured: false,
    rating: 4.3,
    reviews: 62,
    categoryIndex: 4,
    cityIndex: 5,
  },

  // Kolkata
  {
    name: 'Solar Power Company',
    slug: 'solar-power-kolkata',
    description: 'Kolkata\'s leading solar EPC company. Specialized in commercial and industrial projects.',
    phone: '+91 98765 43330',
    email: 'info@solarpowerkolkata.com',
    website: 'https://solarpowerkolkata.com',
    address: 'Salt Lake, Kolkata, West Bengal',
    verified: true,
    featured: true,
    rating: 4.6,
    reviews: 123,
    categoryIndex: 1,
    cityIndex: 6,
  },
  {
    name: 'Bengal Solar Solutions',
    slug: 'bengal-solar-kolkata',
    description: 'West Bengal-based solar installer. PM Surya Ghar Yojana specialist.',
    phone: '+91 98765 43335',
    email: 'info@bengalsolar.com',
    website: 'https://bengalsolar.com',
    address: 'Dum Dum, Kolkata, West Bengal',
    verified: true,
    featured: false,
    rating: 4.4,
    reviews: 86,
    categoryIndex: 0,
    cityIndex: 6,
  },
  {
    name: 'Tata Power Solar - Kolkata',
    slug: 'tata-kolkata',
    description: 'Tata Power Solar authorized partner in East India. Quality installations with trusted service.',
    phone: '+91 98765 43340',
    email: 'kolkata@tatapowersolar.com',
    website: 'https://tatapowersolar.com',
    address: 'Park Street, Kolkata, West Bengal',
    verified: true,
    featured: true,
    rating: 4.7,
    reviews: 176,
    categoryIndex: 0,
    cityIndex: 6,
  },

  // Ahmedabad
  {
    name: 'Gujarat Solar Energy',
    slug: 'gujarat-solar-ahmedabad',
    description: 'Gujarat\'s premier solar EPC company. Solar capital of India\'s leading installer.',
    phone: '+91 98765 43345',
    email: 'info@gujaratsolar.com',
    website: 'https://gujaratsolar.com',
    address: 'Navrangpura, Ahmedabad, Gujarat',
    verified: true,
    featured: true,
    rating: 4.7,
    reviews: 145,
    categoryIndex: 1,
    cityIndex: 7,
  },
  {
    name: 'Waaree Solar - Ahmedabad',
    slug: 'waaree-ahmedabad',
    description: 'Waaree Solar headquarters in Ahmedabad. India\'s largest solar panel manufacturer.',
    phone: '+91 98765 43350',
    email: 'info@waaree.com',
    website: 'https://waaree.com',
    address: 'Bodakdev, Ahmedabad, Gujarat',
    verified: true,
    featured: true,
    rating: 4.8,
    reviews: 234,
    categoryIndex: 2,
    cityIndex: 7,
  },
  {
    name: 'Solar Solutions Ahmedabad',
    slug: 'solar-solutions-ahmedabad',
    description: 'Local solar installation company serving Ahmedabad for 12+ years. Residential focus.',
    phone: '+91 98765 43355',
    email: 'contact@solar-solutions.in',
    website: 'https://solar-solutions.in',
    address: 'Maninagar, Ahmedabad, Gujarat',
    verified: true,
    featured: false,
    rating: 4.5,
    reviews: 98,
    categoryIndex: 0,
    cityIndex: 7,
  },

  // Jaipur
  {
    name: 'Rajasthan Solar Power',
    slug: 'rajasthan-solar-jaipur',
    description: 'Leading solar EPC in Rajasthan. PM Surya Ghar Yojana approved vendor.',
    phone: '+91 98765 43360',
    email: 'info@rajasthansolar.com',
    website: 'https://rajasthansolar.com',
    address: 'Vaishali Nagar, Jaipur, Rajasthan',
    verified: true,
    featured: true,
    rating: 4.6,
    reviews: 112,
    categoryIndex: 1,
    cityIndex: 8,
  },
  {
    name: 'Jaipur Solar Energy',
    slug: 'jaipur-solar',
    description: 'Residential and commercial solar in Jaipur. Free consultation and site survey.',
    phone: '+91 98765 43365',
    email: 'contact@jaipursolar.com',
    website: 'https://jaipursolar.com',
    address: 'C-Scheme, Jaipur, Rajasthan',
    verified: true,
    featured: false,
    rating: 4.4,
    reviews: 78,
    categoryIndex: 0,
    cityIndex: 8,
  },
  {
    name: 'Tata Power Solar - Jaipur',
    slug: 'tata-jaipur',
    description: 'Tata Power Solar in Rajasthan. Quality installations with excellent after-sales support.',
    phone: '+91 98765 43370',
    email: 'jaipur@tatapowersolar.com',
    website: 'https://tatapowersolar.com',
    address: 'Tonk Phatak, Jaipur, Rajasthan',
    verified: true,
    featured: true,
    rating: 4.7,
    reviews: 156,
    categoryIndex: 0,
    cityIndex: 8,
  },

  // Lucknow
  {
    name: 'Uttar Pradesh Solar',
    slug: 'up-solar-lucknow',
    description: 'Leading solar installer in Uttar Pradesh. PM Surya Ghar Yojana specialist.',
    phone: '+91 98765 43375',
    email: 'info@upsolar.com',
    website: 'https://upsolar.in',
    address: 'Gomti Nagar, Lucknow, Uttar Pradesh',
    verified: true,
    featured: true,
    rating: 4.5,
    reviews: 94,
    categoryIndex: 0,
    cityIndex: 9,
  },
  {
    name: 'Lucknow Solar Solutions',
    slug: 'lucknow-solar',
    description: 'Local solar company serving Lucknow and surrounding districts. Residential and commercial.',
    phone: '+91 98765 43380',
    email: 'contact@lucknowsolar.com',
    website: 'https://lucknowsolar.com',
    address: 'Alambagh, Lucknow, Uttar Pradesh',
    verified: true,
    featured: false,
    rating: 4.3,
    reviews: 67,
    categoryIndex: 0,
    cityIndex: 9,
  },
];

// Generate additional listings to reach 100+
const additionalListings = [
  // More residential installers
  { name: 'Shine Solar Energy', slug: 'shine-solar-1', description: 'Affordable residential solar installations.', phone: '+91 98765 50000', categoryIndex: 0, cityIndex: 0 },
  { name: 'Bright Solar Systems', slug: 'bright-solar-1', description: 'Expert in rooftop solar for homes.', phone: '+91 98765 50001', categoryIndex: 0, cityIndex: 1 },
  { name: 'SunBeam Solar', slug: 'sunbeam-solar-1', description: 'Complete home solar solutions.', phone: '+91 98765 50002', categoryIndex: 0, cityIndex: 2 },
  { name: 'Eco Solar India', slug: 'eco-solar-1', description: 'Sustainable energy for homes.', phone: '+91 98765 50003', categoryIndex: 0, cityIndex: 3 },
  { name: 'Pure Energy Solar', slug: 'pure-energy-1', description: 'Clean solar installations.', phone: '+91 98765 50004', categoryIndex: 0, cityIndex: 4 },
  { name: 'Green Planet Solar', slug: 'green-planet-1', description: 'Eco-friendly solar solutions.', phone: '+91 98765 50005', categoryIndex: 0, cityIndex: 5 },
  { name: 'Solar Power Hub', slug: 'solar-hub-1', description: 'Your trusted solar partner.', phone: '+91 98765 50006', categoryIndex: 0, cityIndex: 6 },
  { name: 'Energy Plus Solar', slug: 'energy-plus-1', description: 'Premium residential solar.', phone: '+91 98765 50007', categoryIndex: 0, cityIndex: 7 },
  { name: 'Ray Solar Systems', slug: 'ray-solar-1', description: 'Sun-powered solutions.', phone: '+91 98765 50008', categoryIndex: 0, cityIndex: 8 },
  { name: 'Sunrise Energy', slug: 'sunrise-1', description: 'Morning to night solar power.', phone: '+91 98765 50009', categoryIndex: 0, cityIndex: 9 },

  // More commercial installers
  { name: 'IndoSolar Commercial', slug: 'indo-commercial-1', description: 'Industrial solar specialists.', phone: '+91 98765 50010', categoryIndex: 1, cityIndex: 0 },
  { name: 'Business Solar India', slug: 'business-solar-1', description: 'Corporate solar solutions.', phone: '+91 98765 50011', categoryIndex: 1, cityIndex: 1 },
  { name: 'Enterprise Solar', slug: 'enterprise-solar-1', description: 'Large-scale solar projects.', phone: '+91 98765 50012', categoryIndex: 1, cityIndex: 2 },
  { name: 'Corp Solar Power', slug: 'corp-solar-1', description: 'B2B solar installations.', phone: '+91 98765 50013', categoryIndex: 1, cityIndex: 3 },
  { name: 'Industrial Solar Co', slug: 'industrial-solar-1', description: 'Factory solar experts.', phone: '+91 98765 50014', categoryIndex: 1, cityIndex: 4 },
  { name: 'WareHouse Solar', slug: 'warehouse-solar-1', description: 'Solar for commercial buildings.', phone: '+91 98765 50015', categoryIndex: 1, cityIndex: 5 },
  { name: 'Office Solar India', slug: 'office-solar-1', description: 'Office rooftop solutions.', phone: '+91 98765 50016', categoryIndex: 1, cityIndex: 6 },
  { name: 'Shop Solar Energy', slug: 'shop-solar-1', description: 'Retail solar power.', phone: '+91 98765 50017', categoryIndex: 1, cityIndex: 7 },
  { name: 'Mall Solar Systems', slug: 'mall-solar-1', description: 'Commercial property solar.', phone: '+91 98765 50018', categoryIndex: 1, cityIndex: 8 },
  { name: 'Hotel Solar India', slug: 'hotel-solar-1', description: 'Hospitality sector solar.', phone: '+91 98765 50019', categoryIndex: 1, cityIndex: 9 },

  // More dealers
  { name: 'Solar Depot', slug: 'solar-depot-1', description: 'One-stop solar shop.', phone: '+91 98765 50020', categoryIndex: 2, cityIndex: 0 },
  { name: 'Panel Mart', slug: 'panel-mart-1', description: 'Solar panels wholesale.', phone: '+91 98765 50021', categoryIndex: 2, cityIndex: 1 },
  { name: 'Solar Components India', slug: 'components-1', description: 'All solar parts available.', phone: '+91 98765 50022', categoryIndex: 2, cityIndex: 2 },
  { name: 'PV Systems Dealer', slug: 'pv-dealer-1', description: 'PV panel specialists.', phone: '+91 98765 50023', categoryIndex: 2, cityIndex: 3 },
  { name: 'Rooftop Solar Shop', slug: 'rooftop-shop-1', description: 'Solar for every roof.', phone: '+91 98765 50024', categoryIndex: 2, cityIndex: 4 },
  { name: 'SunStore Solar', slug: 'sunstore-1', description: 'Your solar supermarket.', phone: '+91 98765 50025', categoryIndex: 2, cityIndex: 5 },
  { name: 'India Solar Mart', slug: 'solar-mart-1', description: 'Best solar prices.', phone: '+91 98765 50026', categoryIndex: 2, cityIndex: 6 },
  { name: 'Gujarat Solar Depot', slug: 'gujarat-depot-1', description: 'Gujarat solar hub.', phone: '+91 98765 50027', categoryIndex: 2, cityIndex: 7 },
  { name: 'Rajasthan Solar Shop', slug: 'rajasthan-shop-1', description: 'Local solar dealer.', phone: '+91 98765 50028', categoryIndex: 2, cityIndex: 8 },
  { name: 'UP Solar Mart', slug: 'up-solar-mart-1', description: 'Uttar Pradesh solar.', phone: '+91 98765 50029', categoryIndex: 2, cityIndex: 9 },

  // More inverter specialists
  { name: 'Inverter Tech India', slug: 'inverter-tech-1', description: 'All inverter brands.', phone: '+91 98765 50030', categoryIndex: 3, cityIndex: 0 },
  { name: 'Solar Power Conversion', slug: 'conversion-1', description: 'DC to AC specialists.', phone: '+91 98765 50031', categoryIndex: 3, cityIndex: 1 },
  { name: 'Battery & Inverter Co', slug: 'battery-1', description: 'Energy storage experts.', phone: '+91 98765 50032', categoryIndex: 3, cityIndex: 2 },
  { name: 'Pune Inverter Center', slug: 'pune-inverter-1', description: 'Inverter hub Pune.', phone: '+91 98765 50033', categoryIndex: 3, cityIndex: 3 },
  { name: 'Hyderabad Solar Power', slug: 'hyd-power-1', description: 'Power conversion experts.', phone: '+91 98765 50034', categoryIndex: 3, cityIndex: 4 },
  { name: 'Chennai Inverter Service', slug: 'chennai-service-1', description: 'Inverter repair Chennai.', phone: '+91 98765 50035', categoryIndex: 3, cityIndex: 5 },
  { name: 'Bengal Solar Service', slug: 'bengal-service-1', description: 'East India service.', phone: '+91 98765 50036', categoryIndex: 3, cityIndex: 6 },
  { name: 'Ahmedabad Power Co', slug: 'ahmedabad-power-1', description: 'Gujarat solar service.', phone: '+91 98765 50037', categoryIndex: 3, cityIndex: 7 },
  { name: 'Jaipur Solar Care', slug: 'jaipur-care-1', description: 'Rajasthan service.', phone: '+91 98765 50038', categoryIndex: 3, cityIndex: 8 },
  { name: 'Lucknow Solar Help', slug: 'lucknow-help-1', description: 'UP solar support.', phone: '+91 98765 50039', categoryIndex: 3, cityIndex: 9 },

  // More maintenance services
  { name: 'Solar Care Plus', slug: 'solar-care-plus-1', description: 'Premium AMC services.', phone: '+91 98765 50040', categoryIndex: 4, cityIndex: 0 },
  { name: 'Clean Solar India', slug: 'clean-solar-1', description: 'Panel cleaning experts.', phone: '+91 98765 50041', categoryIndex: 4, cityIndex: 1 },
  { name: 'Solar Maintenance Pro', slug: 'solar-main-pro-1', description: 'Professional O&M.', phone: '+91 98765 50042', categoryIndex: 4, cityIndex: 2 },
  { name: 'Pune Solar AMC', slug: 'pune-amc-1', description: 'Annual maintenance.', phone: '+91 98765 50043', categoryIndex: 4, cityIndex: 3 },
  { name: 'Hyderabad Solar Clean', slug: 'hyd-clean-1', description: 'Telangana service.', phone: '+91 98765 50044', categoryIndex: 4, cityIndex: 4 },
  { name: 'Chennai Solar Service', slug: 'chennai-service-1', description: 'Tamil Nadu maintenance.', phone: '+91 98765 50045', categoryIndex: 4, cityIndex: 5 },
  { name: 'Bengal Solar AMC', slug: 'bengal-amc-1', description: 'West Bengal service.', phone: '+91 98765 50046', categoryIndex: 4, cityIndex: 6 },
  { name: 'Gujarat Solar Care', slug: 'gujarat-care-1', description: 'Gujarat maintenance.', phone: '+91 98765 50047', categoryIndex: 4, cityIndex: 7 },
  { name: 'Rajasthan Solar Help', slug: 'rajasthan-help-1', description: 'Rajasthan AMC.', phone: '+91 98765 50048', categoryIndex: 4, cityIndex: 8 },
  { name: 'UP Solar Service', slug: 'up-service-1', description: 'Uttar Pradesh care.', phone: '+91 98765 50049', categoryIndex: 4, cityIndex: 9 },
];

// Combine all listings
const allListings = [...listings, ...additionalListings];

async function main() {
  console.log('Starting database seed...');

  // Create Categories
  console.log('Creating categories...');
  const createdCategories = await Promise.all(
    categories.map((cat) =>
      prisma.category.upsert({
        where: { slug: cat.slug },
        update: {},
        create: {
          name: cat.name,
          slug: cat.slug,
        },
      })
    )
  );

  // Create Locations
  console.log('Creating locations...');
  const createdLocations = await Promise.all(
    cities.map((city) =>
      prisma.location.upsert({
        where: { slug: city.slug },
        update: {},
        create: {
          city: city.city,
          state: city.state,
          slug: city.slug,
        },
      })
    )
  );

  // Create Listings
  console.log('Creating listings...');
  let count = 0;
  for (const listing of allListings) {
    try {
      await prisma.listing.upsert({
        where: { slug: listing.slug },
        update: {},
        create: {
          name: listing.name,
          slug: listing.slug,
          description: listing.description || null,
          phone: listing.phone,
          email: listing.email || null,
          website: listing.website || null,
          address: listing.address || null,
          verified: listing.verified,
          featured: listing.featured,
          rating: listing.rating,
          reviews: listing.reviews,
          categoryId: createdCategories[listing.categoryIndex].id,
          locationId: createdLocations[listing.cityIndex].id,
        },
      });
      count++;
      console.log(`Created listing ${count}/${allListings.length}: ${listing.name}`);
    } catch (error) {
      console.error(`Error creating ${listing.name}:`, error);
    }
  }

  console.log(`\n✅ Database seeded successfully!`);
  console.log(`   - ${createdCategories.length} categories`);
  console.log(`   - ${createdLocations.length} locations`);
  console.log(`   - ${count} listings`);
}

main()
  .catch((e) => {
    console.error('Error seeding database:', e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
