'use client';

import { useState } from 'react';
import Header from '@/components/Header';
import Footer from '@/components/Footer';
import Breadcrumb from '@/components/ui/Breadcrumb';
import LeadForm from '@/components/LeadForm';
import FAQ from '@/components/ui/FAQ';
import { formatINR, formatLakh } from '@/lib/format';

const STATE_TARIFFS: Record<string, { tariff: number; discom: string }> = {
  Maharashtra: { tariff: 9.5, discom: 'MSEDCL' },
  Gujarat: { tariff: 7.2, discom: 'GUVNL / Torrent' },
  Delhi: { tariff: 8.0, discom: 'BSES / TPDDL' },
  Karnataka: { tariff: 8.5, discom: 'BESCOM' },
  'Uttar Pradesh': { tariff: 7.5, discom: 'UPPCL' },
  Rajasthan: { tariff: 8.2, discom: 'JVVNL / AVVNL' },
  'Tamil Nadu': { tariff: 7.0, discom: 'TANGEDCO' },
  'Madhya Pradesh': { tariff: 7.8, discom: 'MPPKVVCL' },
  Punjab: { tariff: 8.0, discom: 'PSPCL' },
  Haryana: { tariff: 7.5, discom: 'DHBVN / UHBVN' },
  Telangana: { tariff: 8.2, discom: 'TSSPDCL' },
  Kerala: { tariff: 7.6, discom: 'KSEB' },
  'West Bengal': { tariff: 8.5, discom: 'WBSEDCL / CESC' },
  Bihar: { tariff: 7.0, discom: 'NBPDCL / SBPDCL' },
};

export default function SolarSavingsCalculatorPage() {
  const [bill, setBill] = useState<number>(3500);
  const [state, setState] = useState<string>('Maharashtra');
  const [calculated, setCalculated] = useState<boolean>(true);

  // Math calculations
  const stateData = STATE_TARIFFS[state] || { tariff: 8.0, discom: 'State DISCOM' };
  const monthlyUnits = Math.round(bill / stateData.tariff);
  
  // Recommended size: 1kW produces approx 120 units/month in India
  const recommendedKw = Math.max(1, Math.min(10, Math.round((monthlyUnits / 120) * 10) / 10));
  const roundedKw = Math.max(1, Math.min(10, Math.round(recommendedKw)));

  // Financials
  const monthlySolarUnits = roundedKw * 120;
  const offsetUnits = Math.min(monthlyUnits, monthlySolarUnits);
  const monthlySavings = Math.round(offsetUnits * stateData.tariff);
  const annualSavings = monthlySavings * 12;
  const lifetimeSavings = Math.round(annualSavings * 25 * 0.9); // with 10% lifetime degradation discount

  // Approx cost & subsidy
  const grossCost = roundedKw === 1 ? 65000 : roundedKw === 2 ? 130000 : roundedKw === 3 ? 190000 : roundedKw * 58000;
  const subsidy = roundedKw === 1 ? 30000 : roundedKw === 2 ? 60000 : 78000;
  const netInvestment = Math.max(0, grossCost - subsidy);
  const paybackYears = netInvestment > 0 ? (netInvestment / annualSavings).toFixed(1) : '2.5';

  const faqs = [
    {
      q: 'How does rooftop solar reduce my electricity bill to near zero?',
      a: 'With a bi-directional net meter, power generated by your solar panels is consumed directly by your home appliances during daytime. Any excess energy is exported to the electricity grid, earning bill credits that offset the electricity you draw at night.',
    },
    {
      q: 'Will my savings decrease over the 25 years?',
      a: 'Modern Tier-1 ALMM solar panels degrade at less than 0.4% to 0.5% per year, retaining at least 80% to 85% of their original capacity after 25 years. Because utility electricity tariffs rise by 3%–5% annually in India, your financial savings actually increase over time.',
    },
    {
      q: 'Do I still have to pay fixed charges to the DISCOM?',
      a: 'Yes. Most DISCOMs levy a fixed monthly meter connection charge (typically ₹50 to ₹150 per kW of sanctioned load). Even if your net consumption is zero, fixed charges apply.',
    },
  ];

  return (
    <div className="min-h-screen bg-paper text-ink flex flex-col justify-between">
      <Header />

      <div className="border-b border-line bg-paper">
        <div className="max-w-content mx-auto px-4 sm:px-6">
          <Breadcrumb
            items={[
              { label: 'Home', href: '/' },
              { label: 'Tools', href: '/tools/solar-subsidy-calculator' },
              { label: 'Solar Savings Calculator' },
            ]}
          />
        </div>
      </div>

      <section className="border-b border-line bg-paper py-10">
        <div className="max-w-content mx-auto px-4 sm:px-6">
          <h1 className="font-heading font-bold text-3xl sm:text-4xl text-ink leading-tight mb-2">
            Solar Electricity Bill Savings Calculator (India 2026)
          </h1>
          <p className="text-base text-ink-2 max-w-2xl font-body">
            Estimate your monthly bill reduction, 25-year lifetime return, and capital payback period after PM Surya Ghar central subsidies.
          </p>
        </div>
      </section>

      <main className="max-w-content mx-auto px-4 sm:px-6 py-12">
        <div className="grid grid-cols-1 lg:grid-cols-12 gap-10">

          <div className="lg:col-span-8 space-y-12">

            {/* Calculator Card (Inputs on Left, Result on Right) */}
            <div className="border border-line rounded-sm p-6 bg-paper">
              <div className="grid grid-cols-1 md:grid-cols-2 gap-8 items-start">

                {/* Left: Inputs */}
                <div className="space-y-4 font-body">
                  <h2 className="font-heading font-semibold text-lg text-ink">
                    1. Enter your consumption
                  </h2>

                  <div>
                    <label className="block text-xs font-medium text-ink mb-1">
                      Average Monthly Electricity Bill (₹)
                    </label>
                    <input
                      type="number"
                      min={500}
                      max={100000}
                      step={100}
                      value={bill}
                      onChange={(e) => {
                        setBill(Number(e.target.value));
                        setCalculated(true);
                      }}
                      className="w-full h-11 px-3 border border-line rounded-sm bg-paper text-ink text-sm tabular-nums focus:outline-none focus:border-ink focus:ring-1 focus:ring-ink"
                    />
                    <div className="flex gap-1.5 mt-2">
                      {[1500, 3000, 5000, 8000].map((b) => (
                        <button
                          key={b}
                          type="button"
                          onClick={() => setBill(b)}
                          className={`text-xs px-2 py-1 rounded-sm border transition-colors ${
                            bill === b ? 'border-ink bg-ink text-paper' : 'border-line text-ink hover:bg-wash'
                          }`}
                        >
                          ₹{b}
                        </button>
                      ))}
                    </div>
                  </div>

                  <div>
                    <label className="block text-xs font-medium text-ink mb-1">
                      Select Your State
                    </label>
                    <select
                      value={state}
                      onChange={(e) => setState(e.target.value)}
                      className="w-full h-11 px-3 border border-line rounded-sm bg-paper text-ink text-sm focus:outline-none focus:border-ink focus:ring-1 focus:ring-ink"
                    >
                      {Object.keys(STATE_TARIFFS).map((s) => (
                        <option key={s} value={s}>
                          {s} (Avg ₹{STATE_TARIFFS[s].tariff}/unit)
                        </option>
                      ))}
                    </select>
                  </div>

                  <div className="pt-2">
                    <button
                      type="button"
                      onClick={() => setCalculated(true)}
                      className="w-full h-11 bg-sun text-ink font-semibold text-sm rounded-sm hover:brightness-95 transition-colors focus:outline-none focus:ring-2 focus:ring-ink"
                    >
                      Calculate savings
                    </button>
                  </div>
                </div>

                {/* Right: Results in --sun-wash box */}
                <div className="bg-sun-wash border border-sun/40 rounded-sm p-6 space-y-4">
                  <div>
                    <span className="text-xs text-ink-2 uppercase tracking-wide font-medium">Recommended System Capacity</span>
                    <div className="font-heading font-bold text-4xl text-ink mt-0.5 tabular-nums">
                      {roundedKw} kW
                    </div>
                    <p className="text-xs text-ink-2 mt-1">Generates ~{monthlySolarUnits} units / month</p>
                  </div>

                  <div className="border-t border-ink/10 pt-3 space-y-2 text-xs font-body">
                    <div className="flex justify-between items-baseline">
                      <span className="text-ink-2">Monthly bill savings:</span>
                      <strong className="text-ink text-base font-heading tabular-nums">{formatINR(monthlySavings)} / mo</strong>
                    </div>

                    <div className="flex justify-between items-baseline">
                      <span className="text-ink-2">First-year savings:</span>
                      <strong className="text-ink tabular-nums">{formatINR(annualSavings)}</strong>
                    </div>

                    <div className="flex justify-between items-baseline">
                      <span className="text-ink-2">Estimated 25-yr lifetime return:</span>
                      <strong className="text-ink font-heading text-lg tabular-nums">{formatLakh(lifetimeSavings)}</strong>
                    </div>

                    <div className="flex justify-between items-baseline pt-2 border-t border-ink/10">
                      <span className="text-ink font-medium">Estimated capital payback:</span>
                      <strong className="text-ink font-bold tabular-nums">{paybackYears} years</strong>
                    </div>
                  </div>

                  <div className="pt-2">
                    <a
                      href="#quote"
                      className="block text-center w-full py-2.5 bg-ink text-paper font-medium text-xs rounded-sm hover:bg-ink/90 transition-colors"
                    >
                      Get 3 quotes for {roundedKw} kW
                    </a>
                  </div>
                </div>

              </div>
            </div>

            {/* How this is calculated */}
            <section className="space-y-3 font-body text-xs text-ink-2 leading-relaxed">
              <h2 className="font-heading font-semibold text-lg text-ink">
                How this is calculated
              </h2>
              <p>
                Calculations assume average Indian solar irradiance generating 4 units (kWh) per kW of installed capacity per day (120 units per month). Electricity tariff rates are calibrated against 2026 state electricity regulatory commission (SERC) domestic residential tariff slabs.
              </p>
              <p>
                Net installation investment accounts for official <strong>PM Surya Ghar Muft Bijli Yojana</strong> central DBT subsidies (₹30,000 for 1 kW, ₹60,000 for 2 kW, and ₹78,000 for 3 kW or above).
              </p>
            </section>

            {/* FAQs */}
            <section className="border-t border-line pt-8">
              <h2 className="font-heading font-semibold text-2xl text-ink mb-6">
                Frequently asked questions
              </h2>
              <FAQ items={faqs} />
            </section>

          </div>

          <div className="lg:col-span-4 space-y-6 lg:sticky lg:top-6 lg:self-start">
            <LeadForm prefill={{ requirement: `${roundedKw}kW Residential` }} source="tools:savings-calculator" />
          </div>

        </div>
      </main>

      <Footer />
    </div>
  );
}
